name: home_-_particles
timestamp: 1510685900
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1510684978
positions: {  }
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  owlcarousel:
    owlcarousel-2455: 'Owl Carousel'
  custom:
    custom-5807: Intro
    custom-3119: Features
    custom-7658: 'Customer Testimonials'
    custom-6355: 'Develop CMS themes quickly'
  contenttabs:
    contenttabs-3854: 'Content Tabs'
  contentcubes:
    contentcubes-7850: 'Content Cubes'
  messages:
    system-messages-4311: 'System Messages'
  logo:
    logo-2575: 'Logo / Image'
    logo-7138: 'Logo / Image'
  menu:
    menu-7150: Menu
  social:
    social-6279: Social
  copyright:
    copyright-7490: Copyright
  horizontalmenu:
    horizontalmenu-3531: 'Horizontal Menu'
  totop:
    totop-8051: 'To Top'
  mobile-menu:
    mobile-menu-1355: Mobile-menu
inherit:
  default:
    navigation: navigation
    footer: footer
    offcanvas: offcanvas
    system-messages-4311: system-messages-7972
    logo-2575: logo-9608
    menu-7150: menu-6409
    social-6279: social-3171
    logo-7138: logo-9571
    copyright-7490: copyright-1736
    horizontalmenu-3531: horizontalmenu-9034
    totop-8051: totop-8670
    mobile-menu-1355: mobile-menu-5697
